import { Inter } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import BootstrapClient from "@/components/BootstrapClient.js";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Travull App",
    description: "Generated by create next app",
    icons: {
        icon: "/src/app/icon.png",
    },
};

export default function RootLayout({ children }) {
    return (
        <StoreProvider>
            <html lang="en">
                <body
                    className={inter.className}
                    suppressHydrationWarning={true}
                >
                    {children}
                    {/* <BootstrapClient /> */}
                </body>
            </html>
        </StoreProvider>
    );
}
