import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Travull App",
    description: "Generated by create next app",
    icons: {
        icon: "/src/app/icon.png",
    },
};

export default function RootLayout({ children }) {
    return (
        <StoreProvider>
            <html lang="en">
                <body
                    className={inter.className}
                    suppressHydrationWarning={true}
                >
                    {children}
                </body>
            </html>
        </StoreProvider>
    );
}
